name: Atualizar Dados Ibovespa

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar bibliotecas
        run: pip install yfinance pandas

      - name: Criar pastas de suporte
        run: |
          mkdir -p base_de_dados
          mkdir -p arquivos_download

      - name: Executar script de atualização
        run: python update_data.py

      - name: Salvar alterações no repositório
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # O comando abaixo força o Git a reconhecer todas as pastas criadas
          git add base_de_dados/*.json
          git add arquivos_download/*.csv
          # O "|| exit 0" evita que o erro pare o processo se não houver mudanças
          git commit -m "Atualização multi-indicadores: $(date +'%Y-%m-%d')" || exit 0
          git push origin HEAD:main
